# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1750, 954)
        mainwindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.visual_select_img_button = QtWidgets.QPushButton(self.centralwidget)
        self.visual_select_img_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.visual_select_img_button.sizePolicy().hasHeightForWidth())
        self.visual_select_img_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_img_button.setFont(font)
        self.visual_select_img_button.setAutoFillBackground(False)
        self.visual_select_img_button.setCheckable(False)
        self.visual_select_img_button.setAutoRepeat(False)
        self.visual_select_img_button.setAutoExclusive(False)
        self.visual_select_img_button.setAutoDefault(False)
        self.visual_select_img_button.setDefault(False)
        self.visual_select_img_button.setFlat(False)
        self.visual_select_img_button.setObjectName("visual_select_img_button")
        self.horizontalLayout.addWidget(self.visual_select_img_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.visual_img_number_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_img_number_label.setFont(font)
        self.visual_img_number_label.setObjectName("visual_img_number_label")
        self.horizontalLayout.addWidget(self.visual_img_number_label)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.visual_select_img_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_img_lineedit.setFont(font)
        self.visual_select_img_lineedit.setReadOnly(True)
        self.visual_select_img_lineedit.setObjectName("visual_select_img_lineedit")
        self.verticalLayout_2.addWidget(self.visual_select_img_lineedit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.visual_select_gt_label_button = QtWidgets.QPushButton(self.centralwidget)
        self.visual_select_gt_label_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.visual_select_gt_label_button.sizePolicy().hasHeightForWidth())
        self.visual_select_gt_label_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_gt_label_button.setFont(font)
        self.visual_select_gt_label_button.setAutoFillBackground(False)
        self.visual_select_gt_label_button.setCheckable(False)
        self.visual_select_gt_label_button.setAutoRepeat(False)
        self.visual_select_gt_label_button.setAutoExclusive(False)
        self.visual_select_gt_label_button.setAutoDefault(False)
        self.visual_select_gt_label_button.setDefault(False)
        self.visual_select_gt_label_button.setFlat(False)
        self.visual_select_gt_label_button.setObjectName("visual_select_gt_label_button")
        self.horizontalLayout_2.addWidget(self.visual_select_gt_label_button)
        self.visual_label_format_label1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_label_format_label1.sizePolicy().hasHeightForWidth())
        self.visual_label_format_label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_label_format_label1.setFont(font)
        self.visual_label_format_label1.setObjectName("visual_label_format_label1")
        self.horizontalLayout_2.addWidget(self.visual_label_format_label1)
        self.visual_label_format_comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_label_format_comboBox1.sizePolicy().hasHeightForWidth())
        self.visual_label_format_comboBox1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_label_format_comboBox1.setFont(font)
        self.visual_label_format_comboBox1.setEditable(False)
        self.visual_label_format_comboBox1.setCurrentText("")
        self.visual_label_format_comboBox1.setMaxVisibleItems(10)
        self.visual_label_format_comboBox1.setMaxCount(2147483647)
        self.visual_label_format_comboBox1.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.visual_label_format_comboBox1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.visual_label_format_comboBox1.setObjectName("visual_label_format_comboBox1")
        self.horizontalLayout_2.addWidget(self.visual_label_format_comboBox1)
        self.visual_gt_label_number_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_gt_label_number_label.sizePolicy().hasHeightForWidth())
        self.visual_gt_label_number_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_gt_label_number_label.setFont(font)
        self.visual_gt_label_number_label.setObjectName("visual_gt_label_number_label")
        self.horizontalLayout_2.addWidget(self.visual_gt_label_number_label)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.visual_select_gt_label_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_gt_label_lineedit.setFont(font)
        self.visual_select_gt_label_lineedit.setReadOnly(True)
        self.visual_select_gt_label_lineedit.setObjectName("visual_select_gt_label_lineedit")
        self.verticalLayout_2.addWidget(self.visual_select_gt_label_lineedit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.visual_select_det_label_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_select_det_label_button.sizePolicy().hasHeightForWidth())
        self.visual_select_det_label_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_det_label_button.setFont(font)
        self.visual_select_det_label_button.setObjectName("visual_select_det_label_button")
        self.horizontalLayout_4.addWidget(self.visual_select_det_label_button)
        self.visual_label_format_label2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_label_format_label2.sizePolicy().hasHeightForWidth())
        self.visual_label_format_label2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_label_format_label2.setFont(font)
        self.visual_label_format_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.visual_label_format_label2.setObjectName("visual_label_format_label2")
        self.horizontalLayout_4.addWidget(self.visual_label_format_label2)
        self.visual_label_format_comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.visual_label_format_comboBox2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_label_format_comboBox2.sizePolicy().hasHeightForWidth())
        self.visual_label_format_comboBox2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_label_format_comboBox2.setFont(font)
        self.visual_label_format_comboBox2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.visual_label_format_comboBox2.setEditable(False)
        self.visual_label_format_comboBox2.setObjectName("visual_label_format_comboBox2")
        self.horizontalLayout_4.addWidget(self.visual_label_format_comboBox2)
        self.visual_det_label_number_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_det_label_number_label.sizePolicy().hasHeightForWidth())
        self.visual_det_label_number_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_det_label_number_label.setFont(font)
        self.visual_det_label_number_label.setObjectName("visual_det_label_number_label")
        self.horizontalLayout_4.addWidget(self.visual_det_label_number_label)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.visual_select_det_label_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_select_det_label_lineedit.setFont(font)
        self.visual_select_det_label_lineedit.setReadOnly(True)
        self.visual_select_det_label_lineedit.setObjectName("visual_select_det_label_lineedit")
        self.verticalLayout_2.addWidget(self.visual_select_det_label_lineedit)
        self.verticalLayout_13.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.visual_show_gt_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_show_gt_checkbox.setFont(font)
        self.visual_show_gt_checkbox.setObjectName("visual_show_gt_checkbox")
        self.verticalLayout.addWidget(self.visual_show_gt_checkbox)
        self.visual_show_det_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_show_det_checkbox.setFont(font)
        self.visual_show_det_checkbox.setObjectName("visual_show_det_checkbox")
        self.verticalLayout.addWidget(self.visual_show_det_checkbox)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.visual_TP_only_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_TP_only_checkbox.setFont(font)
        self.visual_TP_only_checkbox.setObjectName("visual_TP_only_checkbox")
        self.verticalLayout_5.addWidget(self.visual_TP_only_checkbox)
        self.visual_FP_only_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_FP_only_checkbox.setFont(font)
        self.visual_FP_only_checkbox.setObjectName("visual_FP_only_checkbox")
        self.verticalLayout_5.addWidget(self.visual_FP_only_checkbox)
        self.visual_FN_only_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_FN_only_checkbox.setFont(font)
        self.visual_FN_only_checkbox.setObjectName("visual_FN_only_checkbox")
        self.verticalLayout_5.addWidget(self.visual_FN_only_checkbox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(2, 2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.visual_nms_iou_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_nms_iou_label.setFont(font)
        self.visual_nms_iou_label.setObjectName("visual_nms_iou_label")
        self.verticalLayout_4.addWidget(self.visual_nms_iou_label)
        self.visual_nms_iou_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.visual_nms_iou_horizontalSlider.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_nms_iou_horizontalSlider.setFont(font)
        self.visual_nms_iou_horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visual_nms_iou_horizontalSlider.setAutoFillBackground(False)
        self.visual_nms_iou_horizontalSlider.setMaximum(100)
        self.visual_nms_iou_horizontalSlider.setPageStep(5)
        self.visual_nms_iou_horizontalSlider.setProperty("value", 50)
        self.visual_nms_iou_horizontalSlider.setSliderPosition(50)
        self.visual_nms_iou_horizontalSlider.setTracking(True)
        self.visual_nms_iou_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.visual_nms_iou_horizontalSlider.setInvertedAppearance(False)
        self.visual_nms_iou_horizontalSlider.setInvertedControls(False)
        self.visual_nms_iou_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.visual_nms_iou_horizontalSlider.setTickInterval(10)
        self.visual_nms_iou_horizontalSlider.setObjectName("visual_nms_iou_horizontalSlider")
        self.verticalLayout_4.addWidget(self.visual_nms_iou_horizontalSlider)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.visual_nms_conf_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_nms_conf_label.setFont(font)
        self.visual_nms_conf_label.setObjectName("visual_nms_conf_label")
        self.verticalLayout_10.addWidget(self.visual_nms_conf_label)
        self.visual_nms_conf_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_nms_conf_horizontalSlider.setFont(font)
        self.visual_nms_conf_horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visual_nms_conf_horizontalSlider.setMaximum(100)
        self.visual_nms_conf_horizontalSlider.setProperty("value", 10)
        self.visual_nms_conf_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.visual_nms_conf_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.visual_nms_conf_horizontalSlider.setTickInterval(10)
        self.visual_nms_conf_horizontalSlider.setObjectName("visual_nms_conf_horizontalSlider")
        self.verticalLayout_10.addWidget(self.visual_nms_conf_horizontalSlider)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.visual_iou_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_iou_label.setFont(font)
        self.visual_iou_label.setObjectName("visual_iou_label")
        self.verticalLayout_11.addWidget(self.visual_iou_label)
        self.visual_iou_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_iou_horizontalSlider.setFont(font)
        self.visual_iou_horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visual_iou_horizontalSlider.setMinimum(1)
        self.visual_iou_horizontalSlider.setMaximum(100)
        self.visual_iou_horizontalSlider.setSingleStep(1)
        self.visual_iou_horizontalSlider.setProperty("value", 50)
        self.visual_iou_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.visual_iou_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.visual_iou_horizontalSlider.setTickInterval(10)
        self.visual_iou_horizontalSlider.setObjectName("visual_iou_horizontalSlider")
        self.verticalLayout_11.addWidget(self.visual_iou_horizontalSlider)
        self.verticalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.verticalLayout_3)
        self.visual_message_textedit = QtWidgets.QTextEdit(self.centralwidget)
        self.visual_message_textedit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_message_textedit.setFont(font)
        self.visual_message_textedit.setReadOnly(True)
        self.visual_message_textedit.setObjectName("visual_message_textedit")
        self.verticalLayout_13.addWidget(self.visual_message_textedit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.visual_image_index_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.visual_image_index_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_image_index_lineedit.sizePolicy().hasHeightForWidth())
        self.visual_image_index_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_image_index_lineedit.setFont(font)
        self.visual_image_index_lineedit.setText("")
        self.visual_image_index_lineedit.setFrame(True)
        self.visual_image_index_lineedit.setCursorPosition(0)
        self.visual_image_index_lineedit.setDragEnabled(False)
        self.visual_image_index_lineedit.setReadOnly(False)
        self.visual_image_index_lineedit.setObjectName("visual_image_index_lineedit")
        self.horizontalLayout_8.addWidget(self.visual_image_index_lineedit)
        self.visual_previous_image_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_previous_image_button.setFont(font)
        self.visual_previous_image_button.setObjectName("visual_previous_image_button")
        self.horizontalLayout_8.addWidget(self.visual_previous_image_button)
        self.visual_next_image_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_next_image_button.setFont(font)
        self.visual_next_image_button.setObjectName("visual_next_image_button")
        self.horizontalLayout_8.addWidget(self.visual_next_image_button)
        self.visual_auto_save_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.visual_auto_save_checkbox.setFont(font)
        self.visual_auto_save_checkbox.setObjectName("visual_auto_save_checkbox")
        self.horizontalLayout_8.addWidget(self.visual_auto_save_checkbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.visual_save_single_image_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_save_single_image_button.setFont(font)
        self.visual_save_single_image_button.setObjectName("visual_save_single_image_button")
        self.horizontalLayout_8.addWidget(self.visual_save_single_image_button)
        self.visual_save_all_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_save_all_button.setFont(font)
        self.visual_save_all_button.setObjectName("visual_save_all_button")
        self.horizontalLayout_8.addWidget(self.visual_save_all_button)
        self.visual_save_all_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_save_all_progressBar.sizePolicy().hasHeightForWidth())
        self.visual_save_all_progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.visual_save_all_progressBar.setFont(font)
        self.visual_save_all_progressBar.setProperty("value", 100)
        self.visual_save_all_progressBar.setTextVisible(True)
        self.visual_save_all_progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.visual_save_all_progressBar.setInvertedAppearance(False)
        self.visual_save_all_progressBar.setObjectName("visual_save_all_progressBar")
        self.horizontalLayout_8.addWidget(self.visual_save_all_progressBar)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 2)
        self.horizontalLayout_8.setStretch(2, 2)
        self.horizontalLayout_8.setStretch(4, 4)
        self.horizontalLayout_8.setStretch(5, 2)
        self.horizontalLayout_8.setStretch(6, 2)
        self.horizontalLayout_8.setStretch(7, 4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(2, 5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_10.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_11.addWidget(self.progressBar)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.horizontalLayout_11.setStretch(2, 6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_12.addWidget(self.pushButton_10)
        self.pushButton_25 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_12.addWidget(self.pushButton_25)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_12.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_12.addWidget(self.pushButton_12)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(2, 5)
        self.horizontalLayout_12.setStretch(3, 1)
        self.horizontalLayout_12.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_6.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_13.addWidget(self.comboBox_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(2, 8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_14.addWidget(self.lineEdit_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_14.addWidget(self.pushButton_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_21.addWidget(self.pushButton_23)
        self.progressBar_5 = QtWidgets.QProgressBar(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.horizontalLayout_21.addWidget(self.progressBar_5)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_21.addWidget(self.lineEdit_14)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 2)
        self.horizontalLayout_21.setStretch(2, 6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        spacerItem6 = QtWidgets.QSpacerItem(20, 733, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_22.addWidget(self.lineEdit_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_22.addWidget(self.pushButton_8)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_22.addWidget(self.label_9)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_22.addWidget(self.comboBox_5)
        self.horizontalLayout_22.setStretch(0, 5)
        self.horizontalLayout_22.setStretch(1, 1)
        self.horizontalLayout_22.setStretch(2, 1)
        self.horizontalLayout_22.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_23.addWidget(self.lineEdit_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_23.addWidget(self.pushButton_7)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_23.addWidget(self.label_10)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_23.addWidget(self.comboBox_6)
        self.horizontalLayout_23.setStretch(0, 5)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_23.setStretch(2, 1)
        self.horizontalLayout_23.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_24.addWidget(self.label_4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_24.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_24.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radioButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_3.setIconSize(QtCore.QSize(16, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_24.addWidget(self.radioButton_3)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_24.addWidget(self.pushButton_9)
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_24.addWidget(self.progressBar_2)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_24.addWidget(self.lineEdit_15)
        self.horizontalLayout_24.setStretch(1, 1)
        self.horizontalLayout_24.setStretch(2, 1)
        self.horizontalLayout_24.setStretch(3, 1)
        self.horizontalLayout_24.setStretch(4, 1)
        self.horizontalLayout_24.setStretch(5, 2)
        self.horizontalLayout_24.setStretch(6, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        spacerItem7 = QtWidgets.QSpacerItem(20, 731, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(mainwindow)
        self.statusBar.setObjectName("statusBar")
        mainwindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(mainwindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1750, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuhelp = QtWidgets.QMenu(self.menuBar)
        self.menuhelp.setObjectName("menuhelp")
        mainwindow.setMenuBar(self.menuBar)
        self.actionDocuments = QtWidgets.QAction(mainwindow)
        self.actionDocuments.setObjectName("actionDocuments")
        self.actionNone = QtWidgets.QAction(mainwindow)
        self.actionNone.setObjectName("actionNone")
        self.menuhelp.addAction(self.actionDocuments)
        self.menuBar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(mainwindow)
        self.visual_label_format_comboBox1.setCurrentIndex(-1)
        self.visual_label_format_comboBox2.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "visualizeme"))
        self.visual_select_img_button.setText(_translate("mainwindow", "选择图像文件"))
        self.visual_img_number_label.setText(_translate("mainwindow", "数量: 0"))
        self.visual_select_gt_label_button.setText(_translate("mainwindow", "选择真值标签文件"))
        self.visual_label_format_label1.setText(_translate("mainwindow", "标签格式"))
        self.visual_gt_label_number_label.setText(_translate("mainwindow", "数量: 0"))
        self.visual_select_det_label_button.setText(_translate("mainwindow", "选择检测结果文件"))
        self.visual_label_format_label2.setText(_translate("mainwindow", "标签格式"))
        self.visual_det_label_number_label.setText(_translate("mainwindow", "数量: 0"))
        self.visual_show_gt_checkbox.setText(_translate("mainwindow", "显示真值标签"))
        self.visual_show_det_checkbox.setText(_translate("mainwindow", "显示检测结果"))
        self.visual_TP_only_checkbox.setText(_translate("mainwindow", "仅TP"))
        self.visual_FP_only_checkbox.setText(_translate("mainwindow", "仅FP"))
        self.visual_FN_only_checkbox.setText(_translate("mainwindow", "仅FN"))
        self.visual_nms_iou_label.setText(_translate("mainwindow", "NMS IoU 阈值："))
        self.visual_nms_conf_label.setText(_translate("mainwindow", "NMS 置信度阈值："))
        self.visual_iou_label.setText(_translate("mainwindow", "比对 IoU 阈值："))
        self.visual_image_index_lineedit.setPlaceholderText(_translate("mainwindow", "图像索引"))
        self.visual_previous_image_button.setText(_translate("mainwindow", "上一张"))
        self.visual_next_image_button.setText(_translate("mainwindow", "下一张"))
        self.visual_auto_save_checkbox.setText(_translate("mainwindow", "翻页自动保存"))
        self.visual_save_single_image_button.setText(_translate("mainwindow", "保存单张"))
        self.visual_save_all_button.setText(_translate("mainwindow", "全部保存"))
        self.label_6.setText(_translate("mainwindow", "转换方式"))
        self.pushButton_3.setText(_translate("mainwindow", "选择原始标签路径"))
        self.pushButton_4.setText(_translate("mainwindow", "选择标签保存路径"))
        self.pushButton_5.setText(_translate("mainwindow", "开始转换"))
        self.pushButton_10.setText(_translate("mainwindow", "打开标签文件夹"))
        self.pushButton_25.setText(_translate("mainwindow", "打开标签文件"))
        self.pushButton_11.setText(_translate("mainwindow", "下一个标签"))
        self.pushButton_12.setText(_translate("mainwindow", "上一个标签"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainwindow", "标签格式转换"))
        self.label_7.setText(_translate("mainwindow", "标签格式"))
        self.pushButton_6.setText(_translate("mainwindow", "选择标签文件"))
        self.pushButton_23.setText(_translate("mainwindow", "开始统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainwindow", "标签统计"))
        self.pushButton_8.setText(_translate("mainwindow", "选择真值标签文件"))
        self.label_9.setText(_translate("mainwindow", "标签格式"))
        self.pushButton_7.setText(_translate("mainwindow", "选择检测结果文件"))
        self.label_10.setText(_translate("mainwindow", "标签格式"))
        self.label_4.setText(_translate("mainwindow", "计算方式："))
        self.radioButton_2.setText(_translate("mainwindow", "普通"))
        self.radioButton.setText(_translate("mainwindow", "COCO"))
        self.radioButton_3.setText(_translate("mainwindow", "VOC"))
        self.pushButton_9.setText(_translate("mainwindow", "开始计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainwindow", "指标计算"))
        self.menuhelp.setTitle(_translate("mainwindow", "Help"))
        self.actionDocuments.setText(_translate("mainwindow", "Documents"))
        self.actionNone.setText(_translate("mainwindow", "None"))
